module.exports = {
    youkuNewAnimation:{
        name:'youku',
        address:'http://comic.youku.com/2015',
        desc:'新番'
    },
    tudouNewAnimation:{
        name:'tudou',
        address:'http://zone.tudou.com/tudou_anime',
        desc:'新番'
    },
    iqiyiNewAnimation:{
        name:'iqiyi',
        address:'http://www.iqiyi.com/dongman/bangumi.html',
        desc:'新番'
    },
    pptvNewAnimation:{
        name:'pptv',
        address:'http://cartoon.pptv.com/',
        desc:'新番'
    },
    /*
    bilibiliNewAnimation:{
        name:'bilibili',
        address:'http://www.bilibili.com',
        desc:'新番'
    }*/
};